name: testing trigger events

on:
    push:
    pull_request:
        types: [opened, assigned, reopened, synchronize]
    issues: 
        types: [opened, closed]

jobs:
    testing-events:
        runs-on: ubuntu-latest
        steps:
         - run: |
            echo $GITHUB_SHA
            echo $GITHUB_REF
         - uses: actions/checkout@v6

